// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL45wEulCLGz-LaDaZR7HvhPB0nX4bTPI',
    appId: '1:1027005200040:web:3aeceaadfd9ae7debb349d',
    messagingSenderId: '1027005200040',
    projectId: 'fitnex-5186a',
    authDomain: 'fitnex-5186a.firebaseapp.com',
    storageBucket: 'fitnex-5186a.firebasestorage.app',
    measurementId: 'G-HSNZFKKPE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw3b-LCEnawMmjtAC_oA8u6Y_1rcMprvQ',
    appId: '1:1027005200040:android:c5ce1b26ba758186bb349d',
    messagingSenderId: '1027005200040',
    projectId: 'fitnex-5186a',
    storageBucket: 'fitnex-5186a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL45wEulCLGz-LaDaZR7HvhPB0nX4bTPI',
    appId: '1:1027005200040:web:579e9e9771315392bb349d',
    messagingSenderId: '1027005200040',
    projectId: 'fitnex-5186a',
    authDomain: 'fitnex-5186a.firebaseapp.com',
    storageBucket: 'fitnex-5186a.firebasestorage.app',
    measurementId: 'G-0TMYC8ZV9M',
  );
}
